/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ground.glb 
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect } from "react";

export function Ground(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/ground.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    // ▶ Play ALL animation clips in the GLB
    Object.values(actions).forEach((action) => {
      action.reset().fadeIn(0.5).play();
    });
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <directionalLight
        intensity={1}
        color={"94FFFF"}
        position={[-15, 200, -1000]}
      />
      <pointLight
        intensity={20}
        decay={2}
        distance={10}
        color={"#66ebff"}
        position={[-1, 2, -3]}
      />
      <pointLight
        intensity={30}
        decay={2}
        distance={10}
        color={"yellow"}
        position={[-1, 2, -3]}
      />
      <pointLight
        intensity={100}
        distance={4}
        color={"orange"}
        position={[0, 5, 3]}
      />
      <pointLight
        intensity={3}
        decay={2}
        distance={90}
        color={"#ffea00"}
        position={[0, 1, 0]}
      />
      <pointLight
        intensity={20}
        decay={5}
        distance={3}
        color={"white"}
        position={[-2, 3.5, 1]}
      />
      <pointLight
        intensity={100}
        decay={3}
        distance={100}
        color={"orange"}
        position={[0, 5, -1]}
      />
      <pointLight
        intensity={25}
        decay={4}
        distance={5}
        color={"orange"}
        position={[2, 3, 1]}
      />
      <group name="Scene">
        <group
          name="Empty"
          position={[-9.532, 5, 2.304]}
          rotation={[1.232, -0.06, -1.364]}
        />
        <mesh
          name="Mball005"
          castShadow
          receiveShadow
          geometry={nodes.Mball005.geometry}
          material={materials["Material.021"]}
          position={[1.617, 1.861, 0.498]}
          rotation={[0, -0.552, 0]}
          scale={0.329}
        />
        <mesh
          name="Mball001"
          castShadow
          receiveShadow
          geometry={nodes.Mball001.geometry}
          material={materials.clouds}
          position={[-2.259, 2.967, -0.122]}
          rotation={[2.695, 0.84, -3.128]}
          scale={0.401}
        />
        <mesh
          name="Mball002"
          castShadow
          receiveShadow
          geometry={nodes.Mball002.geometry}
          material={materials.clouds}
          position={[-1.22, 1.156, -2.518]}
          rotation={[-0.287, 0.529, -0.091]}
          scale={0.396}
        />
        <mesh
          name="Mball003"
          castShadow
          receiveShadow
          geometry={nodes.Mball003.geometry}
          material={materials.clouds}
          position={[2.387, 3.006, -1.236]}
          rotation={[-0.673, -0.589, -0.44]}
          scale={0.386}
        />
        <mesh
          name="Mball004"
          castShadow
          receiveShadow
          geometry={nodes.Mball004.geometry}
          material={materials.clouds}
          position={[-1.065, 4.402, -1.967]}
          rotation={[-0.428, 0.022, 0.731]}
          scale={0.382}
        />
        <mesh
          name="Mball006"
          castShadow
          receiveShadow
          geometry={nodes.Mball006.geometry}
          material={materials.clouds}
          position={[1.716, 4.364, -3.306]}
          rotation={[Math.PI, -0.095, Math.PI]}
          scale={0.41}
        />
        <group
          name="Cube019"
          position={[-1.712, 0.391, 0.337]}
          rotation={[Math.PI, -1.341, Math.PI]}
          scale={0.087}
        >
          <mesh
            name="Cube010"
            castShadow
            receiveShadow
            geometry={nodes.Cube010.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            name="Cube010_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_1.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="Cube010_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_2.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            name="Cube010_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_3.geometry}
            material={materials["Material.025"]}
          />
          <mesh
            name="Cube010_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_4.geometry}
            material={materials["Material.024"]}
          />
          <mesh
            name="Cube010_5"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_5.geometry}
            material={materials["Material.026"]}
          />
          <mesh
            name="Cube010_6"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_6.geometry}
            material={materials.Material}
          />
          <mesh
            name="Cube010_7"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_7.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            name="Cube010_8"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_8.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            name="Cube010_9"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_9.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            name="Cube010_10"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_10.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            name="Cube010_11"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_11.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            name="Cube010_12"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_12.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            name="Cube010_13"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_13.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            name="Cube010_14"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_14.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cube010_15"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_15.geometry}
            material={materials["Material.023"]}
          />
          <mesh
            name="Cube010_16"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_16.geometry}
            material={materials["Material.027"]}
          />
        </group>
        <mesh
          name="NurbsPath001"
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath001.geometry}
          material={materials["Material.025"]}
          position={[0.25, 0.36, -0.862]}
          rotation={[0, -0.552, -Math.PI / 2]}
          scale={[0.015, 0.042, 0.042]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ground.glb");
