/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef ,useEffect} from "react";
import { useGLTF, useAnimations} from "@react-three/drei";
import rotateToMouse from "./rotateToMouse";

export function Moon(props) {
  const group = useRef();
  const moon = useRef();
  const { nodes, materials, animations } = useGLTF("/moon.glb");
  
  rotateToMouse(moon);
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    // ▶ Play ALL animation clips in the GLB
    Object.values(actions).forEach((action) => {
      action.reset().fadeIn(0.5).play();
    });
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          ref={moon}
          name="Cylinder001"
          position={[-0.164, 2.963, -0.35]}
          rotation={[1.51, -0.087, -0.04]}
          scale={[1.465, 0.576, 1.465]}>
          <mesh
            name="Cylinder003"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003.geometry}
            material={materials['Material.028']}
            morphTargetDictionary={nodes.Cylinder003.morphTargetDictionary}
            morphTargetInfluences={nodes.Cylinder003.morphTargetInfluences}
          />
          <mesh
            name="Cylinder003_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_1.geometry}
            material={materials['sun5.001']}
            morphTargetDictionary={nodes.Cylinder003_1.morphTargetDictionary}
            morphTargetInfluences={nodes.Cylinder003_1.morphTargetInfluences}
          />
          <mesh
            name="Cylinder003_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_2.geometry}
            material={materials.sun5}
            morphTargetDictionary={nodes.Cylinder003_2.morphTargetDictionary}
            morphTargetInfluences={nodes.Cylinder003_2.morphTargetInfluences}
          />
            <pointLight intensity={8} color={"#A5C9FF"}  decay={2} distance={4} position={[0,3,0]}/>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/moon.glb");
