/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations} from '@react-three/drei'

export function PlaneE(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/groundeve.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    // ▶ Play ALL animation clips in the GLB
    Object.values(actions).forEach((action) => {
      action.reset().fadeIn(0.5).play();
    });
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
        <pointLight intensity={550} color={"#e8baff"} position={[-0.5,3,-4.5]} distance={100} decay={2}/>
      <group name="Scene">
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.sky}
          position={[0, -3.839, 6.578]}
          scale={[84.993, 11.842, 11.842]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/groundeve.glb')
