/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ground.glb 
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect } from "react";

export function PLaneM(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/ground.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    // ▶ Play ALL animation clips in the GLB
    Object.values(actions).forEach((action) => {
      action.reset().fadeIn(0.5).play();
    });
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <pointLight
        intensity={2500}
        decay={3}
        distance={100}
        color={"orange"}
        position={[0, 5, -1]}
      />

      <group name="Scene">
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.sky}
          position={[0, -3.839, 6.578]}
          scale={[84.993, 11.842, 11.842]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ground.glb");
