/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ground.glb 
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect } from "react";

export function PLaneM(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/ground.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    // ▶ Play ALL animation clips in the GLB
    Object.values(actions).forEach((action) => {
      action.reset().fadeIn(0.5).play();
    });
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <directionalLight
        intensity={1}
        color={"94FFFF"}
        position={[-15, 200, -1000]}
      />
      <pointLight
        intensity={20}
        decay={2}
        distance={10}
        color={"#66ebff"}
        position={[-1, 2, -3]}
      />
      <pointLight
        intensity={30}
        decay={2}
        distance={10}
        color={"yellow"}
        position={[-1, 2, -3]}
      />
      <pointLight
        intensity={100}
        distance={4}
        color={"orange"}
        position={[0, 5, 3]}
      />
      <pointLight
        intensity={3}
        decay={2}
        distance={90}
        color={"#ffea00"}
        position={[0, 1, 0]}
      />
      <pointLight
        intensity={20}
        decay={5}
        distance={3}
        color={"white"}
        position={[-2, 3.5, 1]}
      />
      <pointLight
        intensity={100}
        decay={3}
        distance={100}
        color={"orange"}
        position={[0, 5, -1]}
      />
      <pointLight
        intensity={25}
        decay={4}
        distance={5}
        color={"orange"}
        position={[2, 3, 1]}
      />
      <group name="Scene">
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.sky}
          position={[0, -3.839, 6.578]}
          scale={[84.993, 11.842, 11.842]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ground.glb");
