/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations} from '@react-three/drei'

export function PlaneE(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/groundeve.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    // ▶ Play ALL animation clips in the GLB
    Object.values(actions).forEach((action) => {
      action.reset().fadeIn(0.5).play();
    });
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
        <pointLight intensity={20} color={"#ffd675"} position={[1,1,1]} distance={0.9} decay={3}/>
        <pointLight intensity={25} color={"#ffd675"}  position={[-1.8,1,1]} distance={0.9} decay={2}/>
        <pointLight intensity={55} color={"#ffd675"} position={[-0,1.1,-0.9]} distance={0.83} decay={3}/>
        <pointLight intensity={5} color={"#ffd675"} position={[-0.85,0.5,-1]} distance={0.75} decay={3}/>
        <pointLight intensity={55} color={"#ffd675"} position={[0.8,1,-1.5]} distance={0.75} decay={3}/>
        <pointLight intensity={150} color={"#e8baff"} position={[-0.5,1,-4.5]} distance={100} decay={3}/>
        <pointLight intensity={50} color={"#ffde9c"} position={[-0,2,6]} distance={100} decay={2}/>
        <pointLight intensity={50} color={"#e8baff"} position={[-0,3,3]} distance={100} decay={2}/>
        <pointLight intensity={30} color={"#e8baff"} position={[-0,2,-1]} distance={10} decay={4}/>
      <group name="Scene">
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.sky}
          position={[0, -3.839, 6.578]}
          scale={[84.993, 11.842, 11.842]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/groundeve.glb')
