/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef} from 'react'
import { useEffect } from 'react'
import { useGLTF, useAnimations} from '@react-three/drei'
import rotateToMouse from './rotateToMouse'

export function Sun(props) {
  const group = useRef()
  const sun = useRef()
  const { nodes, materials, animations } = useGLTF('/sun.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    // ▶ Play ALL animation clips in the GLB
    Object.values(actions).forEach((action) => {
      action.reset().fadeIn(0.5).play()
    })
 
  }, [actions])
  rotateToMouse(sun)
  return (
    <>
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group ref={sun} onClick={()=>{setRotateTo((p)=>{return p+1})}}
          name="Cylinder002"
          position={[-0.164, 2.963, -0.35]}
          rotation={[1.51, -0.087, -0.04]}
          scale={[1.45, 0.57, 1.45]}>
    
          <mesh
            name="Cylinder001"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={materials.sun}
            morphTargetDictionary={nodes.Cylinder001.morphTargetDictionary}
            morphTargetInfluences={nodes.Cylinder001.morphTargetInfluences}
          />
          <mesh
            name="Cylinder001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.sun5}
            morphTargetDictionary={nodes.Cylinder001_1.morphTargetDictionary}
            morphTargetInfluences={nodes.Cylinder001_1.morphTargetInfluences}
          />
            <pointLight intensity={5} color={"#ff5e00"}  decay={2} distance={2} position={[0,3,0]}/>
        </group>
      </group>
    </group>
    </>
  )
}

useGLTF.preload('/sun.glb')
